import 'api_config.dart';

class ApiConstants {
  static String baseUrl = ApiConfig.baseUrl;

  static String login = "$baseUrl/login";
  static String socialAuth = "$baseUrl/social_login";
  static String registration = "$baseUrl/registration";
  static String changePassword = "$baseUrl/update_password";
  static String emailOtp = "$baseUrl/email_verification";
  static String mobileOtp = "$baseUrl/send_mobile_otp";
  static String verifyEmailOtp = "$baseUrl/validate_otp";
  static String verifyMobileOtp = "$baseUrl/verify_mobile_otp";
  static String forgotPasswordEmail = "$baseUrl/forgot_password_email";
  static String forgotPasswordVerify = "$baseUrl/forgot_password_verify";
  static String forgotNewPassword = "$baseUrl/update_password";
  static String setPassword = "$baseUrl/set_password";
  static String checkUsername =  "$baseUrl/check_username";
  static String userProfile = "$baseUrl/profile";
  static String updateProfile = "$baseUrl/profile";
  static String updatePassword = "$baseUrl/profile/change_password";
  static String updateUsername = "$baseUrl/profile/change_username";
  static String profileImage = "$baseUrl/profile/picture";
  static String coverImage = "$baseUrl/profile/cover";
  static String sendRequest = "$baseUrl/friend_requests";
  static String cancelRequest = "$baseUrl/friend_requests/cancel";
  static String friendRequest = "$baseUrl/friend_requests";
  static String acceptRequest = "$baseUrl/friend_requests";
  static String createGroup = "$baseUrl/chats/group/create";
  static String chatList = "$baseUrl/chats";
  static String renameGroup = "$baseUrl/chats/group";
  static String uploadGroupProfile = "$baseUrl/chats/group";
  static String removeMember = "$baseUrl/chats/group";
  static String deleteGroup = "$baseUrl/chats/group";
  static String leaveGroup = "$baseUrl/chats/group";
  static String makeAdmin = "$baseUrl/chats/group";
  static String addGroupMembers = "$baseUrl/chats/group";
  static String messageList = "$baseUrl/chats";
  static String sendMessage = "$baseUrl/chats";
  static String markAsRead = "$baseUrl/chats";
  static String searchUsers = "$baseUrl/users";
  static String globalSearch = "$baseUrl/global_search";
  static String recentSearch = "$baseUrl/search/recent";
  static String enhancedTrendingHashtags =
      "$baseUrl/trending/hashtags/enhanced";
  static String blockUser = "$baseUrl/users/block";
  static String unBlockUser = "$baseUrl/users/unblock";
  static String blockedUsrsList = "$baseUrl/users/blocked";
  static String userPosts = "$baseUrl/posts";
  static String deletePost = "$baseUrl/posts";
  static String chaseList = "$baseUrl/friends/followers";
  static String reChaseList = "$baseUrl/friends/following";
  static String publicProfile = "$baseUrl/users";
  static String homeFeed = "$baseUrl/home_feed";
  static String singlePost = "$baseUrl/posts";
  static String insights = "$baseUrl/insights";
  static String suggestionUsers = "$baseUrl/users/suggestions";
  static String pollOnThings = "$baseUrl/posts";
  static String notifications = "$baseUrl/notifications";
  static String unreadNotificationCount = "$baseUrl/notifications/unread_count";
  static String markNotificationRead = "$baseUrl/notifications/mark_read";
  static String markAllNotificationsRead =
      "$baseUrl/notifications/mark_all_read";
  static String clearAllNotifications = "$baseUrl/notifications/clear_all";
  static String deleteNotification = "$baseUrl/notifications";
  static String likePost = "$baseUrl/posts";
  static String topVoters = "$baseUrl/polls";
  static String privacyPolicy = "$baseUrl/privacy_status";
  static String feedback = "$baseUrl/feedback/report";
  static String logout = "$baseUrl/logout";
  static String deleteAccount = "$baseUrl/users/delete_account";
}
