name: polzet_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+9

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Icons & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  flutter_screenutil: ^5.9.3
  curved_navigation_bar: ^1.0.6
  lottie: ^3.3.2
  shimmer: ^3.0.0
  glass: ^2.0.0+2
  dotted_border: ^3.1.0
  
  # State Management & Logic
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  local_auth: ^3.0.0
  
  # Networking & Data
  dio: ^5.9.0
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  crypto: ^3.0.3  # Added this to fix your previous error
  
  # Firebase
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  
  # Media & Hardware
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  wechat_assets_picker: ^10.0.0
  wechat_camera_picker: ^4.4.0
  
  # Utils
  fluttertoast: ^9.0.0
  flutter_local_notifications: ^19.5.0
  share_plus: ^12.0.1
  app_links: ^7.0.0
  local_auth_android: ^2.0.4
  path: ^1.9.1
  intl: ^0.20.2
  fl_chart: ^1.1.1
  google_sign_in: ^7.2.0
  showcaseview: ^5.0.2
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  firebase_auth: ^6.5.2
  firebase_app_check: ^0.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # Kept at 3.0.0 for better compatibility with SDK 3.10
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.13.1
  flutter_gen_runner: ^5.13.0+1

flutter_gen:
  output: lib/gen

flutter_launcher_icons: # Fixed name (was flutter_icons)
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_app_foreground.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/ic_app_foreground.png"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: Flexing
      fonts:
        - asset: assets/fonts/flexing-bold.ttf
          weight: 700
        
  