// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8b7ycJqc8-vwWphCUBl3-PLd-k7Dvwus',
    appId: '1:470797111076:web:09dbc5941bf70669f4adb1',
    messagingSenderId: '470797111076',
    projectId: 'polzet-notifications',
    authDomain: 'polzet-notifications.firebaseapp.com',
    storageBucket: 'polzet-notifications.firebasestorage.app',
    measurementId: 'G-MXDGFS57XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ISjRSx1wFRu8rJVWEruGhhcUaUpv0H4',
    appId: '1:470797111076:android:793dbacf8390af66f4adb1',
    messagingSenderId: '470797111076',
    projectId: 'polzet-notifications',
    storageBucket: 'polzet-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-YYmYrZy0sFIBGS0ej8cCCJbh4Ts1kTQ',
    appId: '1:470797111076:ios:731343ba61472f0bf4adb1',
    messagingSenderId: '470797111076',
    projectId: 'polzet-notifications',
    storageBucket: 'polzet-notifications.firebasestorage.app',
    iosBundleId: 'com.example.polzetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-YYmYrZy0sFIBGS0ej8cCCJbh4Ts1kTQ',
    appId: '1:470797111076:ios:731343ba61472f0bf4adb1',
    messagingSenderId: '470797111076',
    projectId: 'polzet-notifications',
    storageBucket: 'polzet-notifications.firebasestorage.app',
    iosBundleId: 'com.example.polzetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8b7ycJqc8-vwWphCUBl3-PLd-k7Dvwus',
    appId: '1:470797111076:web:0579649906becf67f4adb1',
    messagingSenderId: '470797111076',
    projectId: 'polzet-notifications',
    authDomain: 'polzet-notifications.firebaseapp.com',
    storageBucket: 'polzet-notifications.firebasestorage.app',
    measurementId: 'G-D6YKLHVYX5',
  );
}
