// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvOr6v7dz-wQqSzG5zsnU8B6VAuNrJ54',
    appId: '1:423728107242:web:a24a9aa2bfac0c5d1ed193',
    messagingSenderId: '423728107242',
    projectId: 'polzet-a8faa',
    authDomain: 'polzet-a8faa.firebaseapp.com',
    storageBucket: 'polzet-a8faa.firebasestorage.app',
    measurementId: 'G-B8H2BD92MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnyfhH1d1wUWuaosEG5e1SG9CQffHouSA',
    appId: '1:423728107242:android:4dbc5c76751d2e641ed193',
    messagingSenderId: '423728107242',
    projectId: 'polzet-a8faa',
    storageBucket: 'polzet-a8faa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIymc9zms5Erx3SsNQEdNYRsqZVr_Np6Q',
    appId: '1:423728107242:ios:0fc2b2a1c9c0cc2a1ed193',
    messagingSenderId: '423728107242',
    projectId: 'polzet-a8faa',
    storageBucket: 'polzet-a8faa.firebasestorage.app',
    iosBundleId: 'com.example.polzetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIymc9zms5Erx3SsNQEdNYRsqZVr_Np6Q',
    appId: '1:423728107242:ios:0fc2b2a1c9c0cc2a1ed193',
    messagingSenderId: '423728107242',
    projectId: 'polzet-a8faa',
    storageBucket: 'polzet-a8faa.firebasestorage.app',
    iosBundleId: 'com.example.polzetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCvOr6v7dz-wQqSzG5zsnU8B6VAuNrJ54',
    appId: '1:423728107242:web:59010fa92dfb101d1ed193',
    messagingSenderId: '423728107242',
    projectId: 'polzet-a8faa',
    authDomain: 'polzet-a8faa.firebaseapp.com',
    storageBucket: 'polzet-a8faa.firebasestorage.app',
    measurementId: 'G-1BTN9FYQYK',
  );
}
